### ISSUE TITLE
Transfer from pip packaging into git module type packaging 

### ISSUE THREAD

**Issue by rroutsong** [OpenOmics/Dmux#16]
Want to configure the server context git sub module instead of pip packaging

**Comment by skchronicles** [comment]
That sounds good. I just created a [new repo here](https://github.com/OpenOmics/profiles). We can use this repo as a git sub-module for configuring different cluster profiles.
 
 With that being said, let's aim to add/create different Snakemake profiles for each of the clusters: Biowulf, BigSky, Skyline, SLURM (generic option).
